#!/usr/bin/env bash
# This module contains a script that transfers file from client to server

# Function to display usage
usage() {
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
}

# Check if at least 4 arguements are provided
if [ "$#" -lt 4 ]; then
    usage
fi

# Assign input parameters to variables
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Check if the file to transfer exists
if [ ! -f "$PATH_TO_FILE" ]; then
    echo "Error: File '$PATH_TO_FILE' not found."
    exit 1
fi

# Transfer the file using scp with strict host key checking disabled
if scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"; then
    echo "File transferred successfully."
else
    echo "File transfer failed."
    exit 1
fi
