#!/bin/bash
# Installes Nginx on server web-01, listening on port 80 and retiurns a page
# that contains the string 'Hello World'.

# Update the package list
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Create a custom index.html file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Ensure Nginx is listening on port 80
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sed -i 's/listen 

\[::\]

:80 default_server;/listen 

\[::\]

:80;/' /etc/nginx/sites-available/default

# Restart Nginx to apply changes (without using systemctl)
nginx -s stop
nginx

echo "Nginx installation and configuration complete. You can test it using curl localhost."
