#!/usr/bin/env bash
# This script creates a custom 404 error page

# Create the custom 404 error page
cat <<EOT | sudo tee /var/www/html/custom_404.html
<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>Ceci n'est pas une page</h1>
    <p>The page you are looking for could not be found.</p>
</body>
</html>
EOT

# Configure Nginx to use the custom 404 error page
sudo tee /etc/nginx/sites-available/default <<EOT
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
EOT

# Restart Nginx to apply the changes
sudo systemctl restart nginx
