#!/bin/bash
# This script configures a new Ubuntu machine to include a custom HTTP response header

# Update and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Add the custom header to Nginx configuration
sudo sed -i '/server {/a \\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default
