#!/usr/bin/env bash
# Terminates a process using 'kill' command.

process="4-to_infinity_and_beyond"

PID=$(pgrep "$process")

if [ -z "$PID" ]; then
    echo 'Not running'
    exit 1
else
    kill "$PID"
fi
