#!/usr/bin/env bash
# This script prints numbers 1 to 100 by replacing multiples of 3 by 'Fizz', multiples
# of 5 by 'Buzz' and multiples of both 3 & 5 by 'FizzBuzz'.

i=1

while [ $i -le 100 ]
do

    if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
        echo 'FizzBuzz'

    elif [ $((i % 3)) -eq 0 ]; then
        echo 'Fizz'

    elif [ $((i % 5)) -eq 0 ]; then
        echo 'Buzz'

    else
        echo $i

    fi

    ((i++))

done
