#!/usr/bin/env bash
# This script prints hours from 0 to 12 and minutes from 1 to 59 for each hour.

i=0
while [ $i -le 12 ]
do
    echo 'Hour:' $i

    j=1
    while [ $j -lt 60 ]
    do
        echo $j
        ((j++))
    done

    ((i++))
done
