#!/usr/bin/env bash
# This script checks the existance and content of 'school' file and
# displays different messages.

file="school"

if [ -f "$file" ]; then
    echo 'school file exists'

    if [ ! -s "$file" ]; then
        echo 'school file is empty'
    else
        echo 'school file is not empty'
    fi

    echo 'school is a regular file'

else
    echo 'school file does not exist'

fi
